# Generated by Django 3.0.5 on 2020-08-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='video_link',
            field=models.FileField(upload_to='movie_video/'),
        ),
    ]
