# Generated by Django 3.0.5 on 2020-08-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0002_auto_20200801_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='poster',
            field=models.FileField(upload_to='movie_images/'),
        ),
    ]
