# Generated by Django 3.0.5 on 2020-08-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0003_auto_20200801_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='poster',
            field=models.ImageField(max_length=1500, upload_to='movie_images/'),
        ),
    ]
