# Generated by Django 3.0.5 on 2020-08-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0004_auto_20200801_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='video_link',
            field=models.FileField(null=True, upload_to='movie_video/', verbose_name=''),
        ),
    ]
