# Generated by Django 3.0.5 on 2020-08-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0005_auto_20200803_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='length',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminmodel',
            name='plot',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adminmodel',
            name='rating',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminmodel',
            name='rating_votes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminmodel',
            name='trailer_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='adminmodel',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
